name: Publish 'Gold & Currency Tracker'

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Art des Releases'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - alpha
      versionTag:
        description: 'Optional: manueller Tag'
        required: false
      buildRetail:
        description: 'Retail-Version bauen?'
        required: false
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  version-and-tag:
    runs-on: ubuntu-latest
    outputs:
      final_tag: ${{ steps.set-tag.outputs.final_tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ermittle letzten Tag
        id: get-latest
        run: |
          git fetch --tags
          latest=$(git tag --sort=-creatordate | grep '^v' | head -n 1 || echo "v0")
          echo "Letzter Tag: $latest"
          echo "latest_tag=$latest" >> $GITHUB_OUTPUT

      - name: Berechne neuen Tag
        id: set-tag
        run: |
          input="${{ github.event.inputs.versionTag }}"
          type="${{ github.event.inputs.releaseType }}"
          latest="${{ steps.get-latest.outputs.latest_tag }}"

          echo "Ausgangswert: $latest, gewählter Typ: $type"

          if [[ -n "$input" ]]; then
            echo "Benutzerdefinierter Tag: $input"
            echo "final_tag=$input" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Split base and suffix (e.g. v1.2.3-alpha.2)
          base=${latest%%-*}
          suffix=${latest#"$base"}

          # Extrahiere Versionsteile
          version_num=${base#"v"}
          major=$(echo "$version_num" | cut -d. -f1)
          minor=$(echo "$version_num" | cut -d. -f2)
          patch=$(echo "$version_num" | cut -d. -f3)

          if [[ "$suffix" =~ ^-alpha\.[0-9]+$ ]]; then
            alpha_num=$(echo "$suffix" | cut -d. -f2)
          fi

          if [[ "$suffix" =~ ^-alpha\.[0-9]+$ && "$type" == "alpha" ]]; then
            next_alpha=$((alpha_num + 1))
            newtag="v${major}.${minor}.${patch}-alpha.${next_alpha}"
          elif [[ "$suffix" =~ ^-alpha\.[0-9]+$ && "$type" == "release" ]]; then
            newtag="v${major}.${minor}.${patch}"
          elif [[ -z "$suffix" && "$type" == "release" ]]; then
            next_patch=$((patch + 1))
            newtag="v${major}.${minor}.${next_patch}"
          elif [[ -z "$suffix" && "$type" == "alpha" ]]; then
            next_patch=$((patch + 1))
            newtag="v${major}.${minor}.${next_patch}-alpha.1"
          else
            echo "❗ Unerwartete Kombination von vorherigem Tag und Typ"
            exit 1
          fi

          echo "💡 Neuer vorgeschlagener Tag: $newtag"
          echo "final_tag=$newtag" >> $GITHUB_OUTPUT

  create-changelog:
    name: Create Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog section with version header
        run: |
          version="${{ github.event.inputs.versionTag }}"
          date=$(date -u +"%Y-%m-%d")

          echo "**${version} (${date})**" > tmp_changelog.md

          awk '
            /^### \[.*\]/ { if (in_section) exit; in_section = 1; next }
            in_section && /^### \[/ { exit }
            in_section && /^\-/ { print }
          ' CHANGELOG.md >> tmp_changelog.md

          echo "" >> tmp_changelog.md

      - name: Add new block to FULL-CHANGELOG.md
        run: |
            touch FULL-CHANGELOG.md
            cat tmp_changelog.md FULL-CHANGELOG.md > FULL-CHANGELOG.new.md
            mv FULL-CHANGELOG.new.md FULL-CHANGELOG.md

      - name: Commit FULL-CHANGELOG.md
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add FULL-CHANGELOG.md
          git commit -m "Update FULL-CHANGELOG.md für ${{ github.event.inputs.versionTag }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
            
  build-github:
    name: Build Github
    needs: create-changelog
    runs-on: ubuntu-latest
    env:
        GITHUB_OAUTH: ${{ secrets.G_TOKEN }}  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag ${{ github.event.inputs.versionTag }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} refs/tags/${{ github.event.inputs.versionTag }}

      - name: Package and publish for Github (Alpha)
        if: github.event.inputs.releaseType == 'alpha' 
        uses: BigWigsMods/packager@v2

      - name: Package and publish for Github (Release)
        if: github.event.inputs.releaseType != 'alpha' 
        uses: BigWigsMods/packager@v2

  build-retail:
    if: github.event.inputs.buildRetail == 'true'
    name: Build Retail
    needs: build-github
    runs-on: ubuntu-latest
    env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and publish for CourseForge and Wago (Alpha)
        if: github.event.inputs.releaseType == 'alpha'    
        uses: BigWigsMods/packager@v2
        with:
          args: -p 1241700 -a EGPXP3G1

      - name: Package and publish for CourseForge and Wago (Release)
        if: github.event.inputs.releaseType != 'alpha'  
        uses: BigWigsMods/packager@v2
        with:
          args: -p 1241700 -a EGPXP3G1

