name: Publish 'Gold & Currency Tracker'

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Art des Releases'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - alpha
      versionTag:
        description: 'Optional: manueller Tag'
        required: false
      buildRetail:
        description: 'Retail-Version bauen?'
        required: false
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  new-version:
    name: Calculate new version
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.get-latest.outputs.latest_tag }}
      final_tag: ${{ steps.set-tag.outputs.final_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ermittle letzten Git-Tag
        id: get-latest
        run: |
          git fetch --tags
          latest=$(git tag --sort=-creatordate | grep '^v[0-9]' | head -n 1 || echo "v0")
          echo "latest_tag=$latest" >> $GITHUB_OUTPUT

      - name: Berechne neuen Tag
        id: set-tag
        run: |
          input="${{ github.event.inputs.versionTag }}"
          type="${{ github.event.inputs.releaseType }}"
          latest="${{ steps.get-latest.outputs.latest_tag }}"

          if [[ -n "$input" ]]; then
            echo "Benutzerdefinierter Tag: $input"
            echo "final_tag=$input" >> $GITHUB_OUTPUT
            exit 0
          fi

          base=${latest%%-*}
          suffix=${latest#"$base"}
          base_num=${base#"v"}

          if [[ "$suffix" =~ ^-alpha\.[0-9]+$ ]]; then
            alpha_num=$(echo "$suffix" | cut -d. -f2)
          fi

          if [[ "$suffix" =~ ^-alpha\.[0-9]+$ && "$type" == "alpha" ]]; then
            next_alpha=$((alpha_num + 1))
            newtag="v${base_num}-alpha.${next_alpha}"
          elif [[ "$suffix" =~ ^-alpha\.[0-9]+$ && "$type" == "release" ]]; then
            newtag="v${base_num}"
          elif [[ -z "$suffix" && "$type" == "release" ]]; then
            next_base=$((base_num + 1))
            newtag="v${next_base}"
          elif [[ -z "$suffix" && "$type" == "alpha" ]]; then
            next_base=$((base_num + 1))
            newtag="v${next_base}-alpha.1"
          else
            exit 1
          fi

          echo "final_tag=$newtag" >> $GITHUB_OUTPUT

  create-changelog:
    name: Create Changelog
    needs: new-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog section with version header
        run: |
          version="${{ needs.new-version.outputs.final_tag }}"
          date=$(date -u +"%Y-%m-%d")

          echo "**${version} (${date})**" > tmp_changelog.md

          awk '
            /^### \[.*\]/ { if (in_section) exit; in_section = 1; next }
            in_section && /^### \[/ { exit }
            in_section && /^\-/ { print }
          ' CHANGELOG.md >> tmp_changelog.md

          echo "" >> tmp_changelog.md

      - name: Add new block to FULL-CHANGELOG.md
        run: |
            touch FULL-CHANGELOG.md
            cat tmp_changelog.md FULL-CHANGELOG.md > FULL-CHANGELOG.new.md
            mv FULL-CHANGELOG.new.md FULL-CHANGELOG.md

      - name: Commit FULL-CHANGELOG.md
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add FULL-CHANGELOG.md
          git commit -m "Update FULL-CHANGELOG.md für ${{ needs.new-version.outputs.final_tag }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
            
  build-github:
    name: Build Github
    needs: 
      - create-changelog
      - new-version
    runs-on: ubuntu-latest
    env:
        GITHUB_OAUTH: ${{ secrets.G_TOKEN }}  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag ${{ needs.new-version.outputs.final_tag }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} refs/tags/${{ needs.new-version.outputs.final_tag }}

      - name: Ersetze @old-project-version@ in CHANGELOG.md
        run: |
          old_tag="${{ needs.new-version.outputs.latest_tag }}"
           sed -i "s/@old-project-version@/$old_tag/g" CHANGELOG.md

      - name: Package and publish for Github (Alpha)
        if: github.event.inputs.releaseType == 'alpha' 
        uses: BigWigsMods/packager@v2

      - name: Package and publish for Github (Release)
        if: github.event.inputs.releaseType != 'alpha' 
        uses: BigWigsMods/packager@v2

  build-retail:
    if: github.event.inputs.buildRetail == 'true'
    name: Build Retail
    needs: build-github
    runs-on: ubuntu-latest
    env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and publish for CourseForge and Wago (Alpha)
        if: github.event.inputs.releaseType == 'alpha'    
        uses: BigWigsMods/packager@v2
        with:
          args: -p 1241700 -a EGPXP3G1

      - name: Package and publish for CourseForge and Wago (Release)
        if: github.event.inputs.releaseType != 'alpha'  
        uses: BigWigsMods/packager@v2
        with:
          args: -p 1241700 -a EGPXP3G1

